
# Base URL
baseurl:

# Site live URL
url: https://toyknight.net

config:
  name: net.toyknight.home
  description:
  meta_description: > #
    Definitely NOT a tech blog.
    http://toyknight.net

  # Profile links, leave blank to ignore
  social:
    github: toyknight
    twitter: lp_gong
    facebook:
    gplus:
    dribble:
    pinterest:

markdown: kramdown
highlighter: rouge

# Disqus
disqus:
  id: "toyknight"

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

plugins:
  - jemoji
