
# Base URL
baseurl:

# Site live URL
url: https://toyknight.net

harmony:
  name: net.toyknight.home
  description:
  meta_description: > #
    Definitely NOT a tech blog.
    http://toyknight.net
  basetheme: theme-base-01  # pre defined themes are darken, blue-water, redish.
  #Author of harmony
  author:
    name: Gayan Virajith
    email: gayanvirajith@gmail.com
    url: http://gayanvirajith.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key:

  # Profile links, leave blank to ignore
  social:
    github: toyknight
    twitter: lp_gong
    facebook:
    gplus:
    dribble:
    pinterest:
  # Toggle disclaimer in footer
  show_disclaimer: true

markdown: kramdown
highlighter: rouge

# Disqus
disqus:
  id: "toyknight"

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
style: :compressed

plugins:
  - jemoji
